apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-service
spec:
  selector:    
    app: dash-test
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 8050
    protocol: TCP